spring:
  application:
    name: tcc-rm-one
  cloud:
    alibaba:
      seata:
        tx-service-group: my_test_tx_group

server:
  port: 8080

eureka:
  client:
    service-url:
      defaultZone: http://192.168.202.137:8761/eureka/
  instance:
    prefer-ip-address: true
    instance-id: ${spring.cloud.client.ip-address}:${server.port}